Downloading Logstash & Kibana instedof packaging, create standard config if one not found.
[X]Downloading Logstash instead of packaging.
[X]Downloading Kibana instead of packaging.
[X]Add standard config if a config is not present.

diff --git a/spk/logstash/src/scripts/start-stop-status b/spk/logstash/src/scripts/start-stop-status
--- a/spk/logstash/src/scripts/start-stop-status
+++ b/spk/logstash/src/scripts/start-stop-status
@@ -1,22 +1,17 @@
 #!/bin/sh
 # Copyright (c) 2013-2014 AustinSaintAubin. All rights reserved.
 # https://github.com/mrlesmithjr/Logstash_Kibana3/blob/master/install_logstash_kibana_ubuntu.sh
-# logstash-1.3.3-noarch-0011
+# logstash-1.3.3-noarch-0012
 
 # PATH="${INSTALL_DIR}/bin:/usr/local/bin:/bin:/usr/bin:/usr/syno/bin"
-source /root/.profile  # Get Environment Variables
-# source $(pwd)/common.sh  # load common settings
+source /root/.profile  # Get Environment Variables from Root Profile
 
-PACKAGE_NAME="logstash"  # "$(echo "$SYNOPKG_PKGNAME" | awk '{print tolower($0)}' | sed -e 's/ /_/g')"
-PACKAGE_DIR="/var/packages/${PACKAGE_NAME}/target"  # "$SYNOPKG_PKGDEST"
-PACKAGE_UPGRADE_FLAG="/tmp/${PACKAGE_NAME}.upgrade"
+PACKAGE_NAME_SIMPLE="@package_name_simple@"  # "$(echo "$SYNOPKG_PKGNAME" | awk '{print tolower($0)}' | sed -e 's/ /_/g')"
+PACKAGE_DIR="@package_dir@"  # "$SYNOPKG_PKGDEST"
+PACKAGE_UPGRADE_FLAG="@package_upgrade_flag@"
 
 # Logstash Varables
-LOGSTASH_JAR_FILE="logstash-1.3.3-flatjar.jar"
-LOGSTASH_USER_DIRECTORY="/volume1/active_system/$PACKAGE_NAME"
-# LOGSTASH_CONFIG_PATH="$LOGSTASH_USER_DIRECTORY/logstash.conf"
-# LOGSTASH_DATABASE_DIR="$LOGSTASH_USER_DIRECTORY/database"  # https://logstash.jira.com/browse/LOGSTASH-125
-# LOGSTASH_LOG_PATH="${PACKAGE_DIR}/$PACKAGE_NAME.log"
+LOGSTASH_JAR_FILE="@logstash_jar_file@"
 LOGSTASH_CONFIG_PATH="@logstash_config_path@"
 LOGSTASH_DATABASE_DIR="@logstash_database_dir@"  # https://logstash.jira.com/browse/LOGSTASH-125
 LOGSTASH_LOG_PATH="@logstash_log_path@"
@@ -37,16 +32,17 @@ JAVA_ARGS_TUNING="$JAVA_ARGS_TUNING @java_args_tuning@"
 JAVA_ARGS="$JAVA_ARGS_TUNING -Des.path.data="${LOGSTASH_DATABASE_DIR}" -jar "$JAVA_PACKAGE_JAR_PATH" $JAVA_PACKAGE_JAR_ARGS"
 
 # Start & Stop Varables
-PID_FILE="/var/run/$PACKAGE_NAME.pid"
+PID_FILE="/var/run/${PACKAGE_NAME_SIMPLE}.pid"
 
 
 DaemonStart() {
 	DaemonStatus
 	if [ $? == 0 ]; then
-		echo "Starting $PACKAGE_NAME."
+		echo "Starting ${PACKAGE_NAME_SIMPLE}."
 		rm -f "$LOGSTASH_LOG_PATH"
-		echo "Starting $PACKAGE_NAME. $(date) [$PACKAGE_NAME] ( $PACKAGE_DIR )" >> "$LOGSTASH_LOG_PATH"
+		echo "Starting ${PACKAGE_NAME_SIMPLE}. $(date) [${PACKAGE_NAME_SIMPLE}] ( $JAVA_PACKAGE_JAR_PATH )" >> "$LOGSTASH_LOG_PATH"
 		echo " ...Might take a moment to be fully initialize logstash... please wait." >> "$LOGSTASH_LOG_PATH"
+		[ -e "${LOGSTASH_CONFIG_PATH}" ] || ( cp "${SYNOPKG_PKGDEST}/logstash-sample.conf" "${LOGSTASH_CONFIG_PATH}"; echo "Config not found, loading sample config." >> "$LOGSTASH_LOG_PATH" )
 		echo "Using Elasticsearch database at ${LOGSTASH_DATABASE_DIR}." >> "$LOGSTASH_LOG_PATH"
 # 		nohup $JAVA_BINARY -jar "$JAVA_PACKAGE_JAR_PATH" $JAVA_PACKAGE_JAR_ARGS >> "$LOGSTASH_LOG_PATH" 2>&1&
 # 		nohup java -jar "$JAVA_PACKAGE_JAR_PATH" $JAVA_PACKAGE_JAR_ARGS >> "$LOGSTASH_LOG_PATH" 2>&1&
@@ -55,14 +51,14 @@ DaemonStart() {
 		nohup java $JAVA_ARGS >> "$LOGSTASH_LOG_PATH" 2>&1&
 		echo $! > "$PID_FILE"		
 	else
-		echo "$PACKAGE_NAME already running."
+		echo "${PACKAGE_NAME_SIMPLE} already running."
 	fi
 }
 
 DaemonDebug() {
 	DaemonStatus
 	if [ $? == 0 ]; then
-		echo "Starting $PACKAGE_NAME."
+		echo "Starting ${PACKAGE_NAME_SIMPLE}."
 # 		java -jar "$JAVA_PACKAGE_JAR_PATH" $JAVA_PACKAGE_JAR_ARGS
 		java $JAVA_ARGS
 	fi
@@ -71,13 +67,13 @@ DaemonDebug() {
 DaemonStop() {
 	DaemonStatus
 	if [ $? == 1 ]; then
-		echo "Stopping $PACKAGE_NAME."
+		echo "Stopping ${PACKAGE_NAME_SIMPLE}."
 		kill $(cat "$PID_FILE");
 		rm -f "$PID_FILE"
 		
 		sleep 3
 	else
-		echo "Nothing to stop for $PACKAGE_NAME."
+		echo "Nothing to stop for ${PACKAGE_NAME_SIMPLE}."
 	fi
 }
 
@@ -86,15 +82,15 @@ DaemonStatus() {
 		PID=$(cat "$PID_FILE")
 		
 		if [ -n "$(ps | grep $PID | grep -vn "grep $PID")" ]; then
-			echo "$PACKAGE_NAME is running ..."
+			echo "${PACKAGE_NAME_SIMPLE} is running ..."
 			return 1  # is running
 		else
-			echo "$PACKAGE_NAME is NOT running ..."
+			echo "${PACKAGE_NAME_SIMPLE} is NOT running ..."
 			rm -f ${PID_FILE}  # Remove Invalid PID
 			return 0  # is NOT running
 		fi
 	else
-		echo "$PACKAGE_NAME is NOT running ...."
+		echo "${PACKAGE_NAME_SIMPLE} is NOT running ...."
 		return 0  # is NOT running
 	fi
 }
